.nh
.TH "interchange" "1" "Apr 2023" "" ""

.SH NAME
.PP
interchange-doc - generate documentation for interchange


.SH SYNOPSIS
.PP
\fBinterchange doc [flags]\fP


.SH DESCRIPTION
.PP
generate documentation for interchange in several formats


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for doc

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBinterchange(1)\fP, \fBinterchange-doc-man(1)\fP, \fBinterchange-doc-md(1)\fP
