.nh
.TH "interchange" "1" "Apr 2023" "" ""

.SH NAME
.PP
interchange - A tcp and udp forwarder


.SH SYNOPSIS
.PP
\fBinterchange [flags]\fP


.SH DESCRIPTION
.PP
A tcp and udp forwarder


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for interchange

.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBinterchange-completion(1)\fP, \fBinterchange-doc(1)\fP, \fBinterchange-fwd(1)\fP
