.nh
.TH "interchange" "1" "Oct 2021" "" ""

.SH NAME
.PP
interchange\-fwd \- Forwards tcp and udp traffic


.SH SYNOPSIS
.PP
\fBinterchange fwd [flags]\fP


.SH DESCRIPTION
.PP
Forwards tcp and udp traffic


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for fwd

.PP
\fB\-t\fP, \fB\-\-tcp\fP=[]
	forward tcp ports (SRCPORT:TARGETHOST:TARGETPORT); may be specified multiple times

.PP
\fB\-u\fP, \fB\-\-udp\fP=[]
	forward udp ports (SRCPORT:TARGETHOST:TARGETPORT); may be specified multiple times

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
	enable verbose logging


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $XDG\_CONFIG\_HOME/.interchange.yaml)

.PP
\fB\-\-debug\fP[=false]
	turn on debug output


.SH SEE ALSO
.PP
\fBinterchange(1)\fP
