.nh
.TH "interchange" "1" "Apr 2023" "" ""

.SH NAME
.PP
interchange-fwd - Forwards tcp and udp traffic


.SH SYNOPSIS
.PP
\fBinterchange fwd [flags]\fP


.SH DESCRIPTION
.PP
Forwards tcp and udp traffic


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for fwd

.PP
\fB-t\fP, \fB--tcp\fP=[]
	forward tcp ports (SRCPORT:TARGETHOST:TARGETPORT); may be specified multiple times

.PP
\fB--tcp-timeout\fP=10s
	tcp conn timeout

.PP
\fB-u\fP, \fB--udp\fP=[]
	forward udp ports (SRCPORT:TARGETHOST:TARGETPORT); may be specified multiple times

.PP
\fB--udp-timeout\fP=10s
	udp conn timeout


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBinterchange(1)\fP
