.nh
.TH "interchange" "1" "Apr 2023" "" ""

.SH NAME
.PP
interchange-doc-man - generate man page documentation for interchange


.SH SYNOPSIS
.PP
\fBinterchange doc man [flags]\fP


.SH DESCRIPTION
.PP
generate man page documentation for interchange


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for man


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--log-level\fP="info"
	log level

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH SEE ALSO
.PP
\fBinterchange-doc(1)\fP
