.nh
.TH "interchange" "1" "Oct 2021" "" ""

.SH NAME
.PP
interchange \- A tcp and udp forwarder


.SH SYNOPSIS
.PP
\fBinterchange [flags]\fP


.SH DESCRIPTION
.PP
A tcp and udp forwarder


.SH OPTIONS
.PP
\fB\-\-config\fP=""
	config file (default is $XDG\_CONFIG\_HOME/.interchange.yaml)

.PP
\fB\-\-debug\fP[=false]
	turn on debug output

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for interchange


.SH SEE ALSO
.PP
\fBinterchange\-completion(1)\fP, \fBinterchange\-doc(1)\fP, \fBinterchange\-fwd(1)\fP
