.nh
.TH "interchange" "1" "Oct 2021" "" ""

.SH NAME
.PP
interchange\-doc \- generate documentation for interchange


.SH SYNOPSIS
.PP
\fBinterchange doc [flags]\fP


.SH DESCRIPTION
.PP
generate documentation for interchange in several formats


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for doc

.PP
\fB\-o\fP, \fB\-\-output\fP="."
	documentation output path


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $XDG\_CONFIG\_HOME/.interchange.yaml)

.PP
\fB\-\-debug\fP[=false]
	turn on debug output


.SH SEE ALSO
.PP
\fBinterchange(1)\fP, \fBinterchange\-doc\-man(1)\fP, \fBinterchange\-doc\-md(1)\fP
